export {default as Register} from "./register"
export {default as Login} from "./login"
export {default as App} from "./app"
export {default as Posts} from "./posts"
export {default as CreatePost} from "./createpost"
export {default as NavBar} from "./home"
export {default as UpdatePost} from "./updateposts"
export {default as Message} from "./message"